name: Say hello

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: windows-latest
    steps:
      - name: Echo Hello world action steps
        run: echo "Hello world!"

      - name: Time stamp
        run: echo The time is $(Get-Date)
      